### ISSUE TITLE
Paper URL

### ISSUE THREAD

**Issue by xiewende** [HunterJ-Lin/ActiveTeacher#1]
the URL of this paper missed，could you provide it？

**Comment by HunterJ-Lin** [comment]
> the URL of this paper missed，could you provide it？

Since CVPR2022 has not released the paper yet, if you need it, you can contact hunterjlin007@gmail.com for the draft

**Comment by HunterJ-Lin** [comment]
> the URL of this paper missed，could you provide it？

hello, this paper has been released. https://openaccess.thecvf.com/content/CVPR2022/papers/Mi_Active_Teacher_for_Semi-Supervised_Object_Detection_CVPR_2022_paper.pdf
