### ISSUE TITLE
'Non-existent config key: DATASETS.CROSS_DATASET'

### ISSUE THREAD

**Issue by sijie-Xu** [HunterJ-Lin/ActiveTeacher#3]
你好!
![image](https://user-images.githubusercontent.com/122505422/227139229-f62bade9-e839-44e5-9f51-de3c8c2d07f1.png)
我按照coco的数据集流程试图训练voc07+12数据集，但是发生了这样的错误：
![image](https://user-images.githubusercontent.com/122505422/227139622-3da0ca29-5e96-4f42-8eb3-719fe07f5c85.png)

我不确定这段代码是不是需要改变
![image](https://user-images.githubusercontent.com/122505422/227140331-ff84e948-5642-4e07-9fe0-0b0146e6a09f.png)

或者在开始的时候选择出现问题
python tools/generate_random_data_partition.py --random-file dataseed/VOC07+VOC12_supervision.txt --random-percent 5.0 --datasets "voc_2007_trainval"
python tools/generate_random_data_partition.py --random-file dataseed/VOC07+VOC12_supervision.txt --random-percent 5.0 --datasets "voc_2012_trainval"

如果能提供解答，十分感谢！

**Comment by HunterJ-Lin** [comment]
已修复bug，感谢反馈
