### ISSUE TITLE
复现条件

### ISSUE THREAD

**Issue by shaun-tim** [HunterJ-Lin/ActiveTeacher#4]
感谢作者，请问如果想复现代码至少需要怎样的硬件条件呢？

**Comment by HunterJ-Lin** [comment]
我们是在8张V100跑的，batch size为32 label，32 unlabel。此外，我们也跑了16+16batch size的1，2，5，10，20比例下的训练好的模型，这个需要4张3090。mAP相比之下都会低0.x个点，分别为( 22.20->21.33), (24.99->24.25), (30.07->29.35), (32.58->31.94), (35.49->35.14)。 据我们后续实验发现，这个框架对batch size是较为敏感的。（加了mask分支后，我们也发现小batch size下，把unsup loss weight从4.0调成2.0是有帮助的

**Comment by shaun-tim** [comment]
好的好的，非常感谢
