### ISSUE TITLE
When I was training my custom data, I ran into problems. How do I get the coco_regulation.txt file?

### ISSUE THREAD

**Issue by AddPear** [HunterJ-Lin/ActiveTeacher#5]

**Comment by HunterJ-Lin** [comment]
What is 'coco_regulation.txt' mean?
1、If you want to get supervised and unsupervised data partitioning of your custom dataset, i.e. 'YOUR_CUSTOM_supervision.txt', please use the following code
https://github.com/HunterJ-Lin/ActiveTeacher/blob/main/tools/generate_random_data_partition.py
2、If you want to get the data partition selected by active learning, please first use the data divided in 1 to train a model for active selection, then follow 'Step 2, Step3' in README.md to get ‘YOUR_CUSTOM_active_pick.txt’
