### ISSUE TITLE
请问如何使用自定义数据集

### ISSUE THREAD

**Issue by lualualualu** [HunterJ-Lin/ActiveTeacher#6]

**Comment by HunterJ-Lin** [comment]
1、参考https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html或者https://github.com/shenyunhang/DRN-WSOD-pytorch/blob/DRN-WSOD/projects/WSL/wsl/data/datasets/builtin.py#L42自定义并注册数据集
2、使用https://github.com/HunterJ-Lin/ActiveTeacher/blob/main/tools/generate_random_data_partition.py划分有标注的数据集，如标注5%，python tools/generate_random_data_partition.py --random-file dataseed/customed_dataset_supervision.txt --random-percent 5.0 --datasets "customed_dataset_train,"
